### PR TITLE
Adding Print Button on AdminPage

### PR DESCRIPTION
**Pull request by sherrif10**
cc @prapakaransp  @sharvanan

### CODE REVIEW

**Comment by sherrif10** [comment]
rint
and this one

**Comment by sherrif10** [comment]
Hello @prapakaransp  @sharvanan  do you think this is worth it ,could you add some pointers here

**Comment by prapakaransp** [comment]
@sherrif10  We may need option to display clinic name in top and also need to attached this bundle with distro module.

**Comment by sherrif10** [comment]
Sure i think for options to display clinic name would be configurable, could you specify any clinic name i try it first

**Comment by sherrif10** [comment]
This module will not be attached into distro because it is not on maven of openmrs , we can only bundle this module if its part of openmrs as whole, remember this module was on person basis not the community

**Comment by sherrif10** [comment]
sreen
So for this kind of clinic name we need to configure it there like how i added the link, we can only replace the string to the clinic name, let me know if this satifies our use case

**Comment by sherrif10** [comment]
Screenshot from 2021-03-23 16-48-24
Formatted button

**Comment by sherrif10** [comment]
cc @prapakaransp  how does this look now

**Pull request merged**
